services:
    webapp:
        build:
            dockerfile: .configs/php-fpm.Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mariadb:lts
        restart: always
        volumes:
            - ./database/db-files:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}

    nginx:
        image: nginx
        volumes:
            - .:/var/www/html
            - .configs/lande.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - webapp
        ports:
            - "80:80"
